# Generated by Django 5.2.15 on 2026-07-09 13:25

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models


def create_pattern_idx(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('CREATE INDEX IF NOT EXISTS en_word_lower_pattern_idx ON dictionary_en_enword ((lower(word)) varchar_pattern_ops);')


def drop_pattern_idx(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP INDEX IF EXISTS en_word_lower_pattern_idx;')


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_en', '0005_alter_enword_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enword',
            index=models.Index(django.db.models.functions.text.Lower('word'), name='en_word_lower_btree_idx'),
        ),
        migrations.AddIndex(
            model_name='enword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['translation_vi'], name='enword_trans_vi_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.RunPython(
            create_pattern_idx,
            reverse_code=drop_pattern_idx,
        ),
    ]

