# Generated by Django 5.2.15 on 2026-07-13 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=20, unique=True)),
                ('weekly_refill_cap', models.IntegerField(default=0, help_text='Mức hồi paid_balance tối đa mỗi tuần')),
                ('initial_coins_zh', models.IntegerField(default=0, help_text='Linh Thạch khởi tạo (paid) cho user mới')),
                ('initial_coins_en', models.IntegerField(default=0, help_text='Coin EN khởi tạo (paid) cho user mới')),
                ('words_per_coin', models.IntegerField(default=5, help_text='Số từ thuộc = 1 coin (free)')),
                ('chat_create_cost', models.IntegerField(default=5, help_text='Chi phí tạo AI Persona')),
                ('chat_message_cost', models.IntegerField(default=1, help_text='Chi phí gửi tin nhắn AI')),
            ],
        ),
        migrations.CreateModel(
            name='CoinPurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(choices=[('zh', 'Linh Thạch'), ('en', 'Coin')], max_length=10)),
                ('coin_amount', models.IntegerField(help_text='Số coin sẽ nhận')),
                ('price', models.DecimalField(decimal_places=0, help_text='Số tiền VNĐ', max_digits=12)),
                ('order_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('transfer_content', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('EXPIRED', 'Hết hạn')], default='PENDING', max_length=10)),
                ('sepay_transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('bank_reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(choices=[('zh', 'Linh Thạch'), ('en', 'Coin')], max_length=10)),
                ('paid_balance', models.IntegerField(default=0, help_text='Coin refill/mua — trừ trước')),
                ('free_balance', models.IntegerField(default=0, help_text='Coin kiếm từ học — trừ sau')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Đang học'), ('FINISHED', 'Hoàn thành'), ('ABANDONED', 'Bỏ dở')], default='IN_PROGRESS', max_length=20)),
                ('total_cards', models.IntegerField(default=0)),
                ('memorized_count', models.IntegerField(default=0)),
                ('coins_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Liên kết các bản ghi thuộc cùng 1 giao dịch logic (split spend)')),
                ('transaction_type', models.CharField(choices=[('EARN_STUDY', 'Kiếm từ học flashcard'), ('SPEND_CHAT_CREATE', 'Tạo AI Persona'), ('SPEND_CHAT_MSG', 'Gửi tin nhắn AI Chat'), ('REFUND', 'Hoàn trả do lỗi'), ('WEEKLY_REFILL', 'Hồi điểm hàng tuần'), ('ADMIN_ADJUST', 'Admin điều chỉnh'), ('PURCHASE', 'Mua bằng tiền'), ('TIER_RESET', 'Reset khi hết hạn subscription')], max_length=30)),
                ('balance_type', models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], help_text='Nguồn cấp thực tế bị tác động', max_length=10)),
                ('amount', models.IntegerField(help_text='Dương = cộng, Âm = trừ. Giá trị chính xác theo balance_type')),
                ('paid_balance_after', models.IntegerField(help_text='Snapshot paid_balance sau giao dịch')),
                ('free_balance_after', models.IntegerField(help_text='Snapshot free_balance sau giao dịch')),
                ('reference_id', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gamification.coinwallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='gamificatio_user_id_b3bf1e_idx'), models.Index(fields=['wallet', 'created_at'], name='gamificatio_wallet__5032ca_idx'), models.Index(fields=['group_id'], name='gamificatio_group_i_a7e65d_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudySessionCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_id', models.UUIDField(help_text='FK tới FlashcardExercise.id')),
                ('word', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Chưa lật'), ('memorized', 'Đã thuộc'), ('skipped', 'Bỏ qua')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_cards', to='gamification.studysession')),
            ],
            options={
                'unique_together': {('session', 'card_id')},
            },
        ),
    ]
