# Generated by Django 5.2.15 on 2026-07-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_coinconfig_coinpurchaseorder_coinwallet_studysession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinconfig',
            name='tier',
            field=models.CharField(choices=[('Free', 'Free'), ('Plus', 'Plus'), ('Pro', 'Pro'), ('Premium', 'Premium')], help_text='Gói đăng ký tương ứng', max_length=20, unique=True),
        ),
    ]
