# Generated by Django 5.2.15 on 2026-07-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_coinconfig_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinconfig',
            name='daily_free_earn_limit',
            field=models.IntegerField(default=50, help_text='Giới hạn số coin free tối đa có thể kiếm mỗi ngày (0 = không giới hạn)'),
        ),
    ]
