# Generated by Django 5.2.15 on 2026-07-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_coinconfig_daily_free_earn_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinconfig',
            name='pdf_normal_export_cost',
            field=models.IntegerField(default=2, help_text='Chi phí Linh Thạch cho xuất PDF thường khi quá hạn'),
        ),
        migrations.AddField(
            model_name='coinconfig',
            name='pdf_stroke_export_cost',
            field=models.IntegerField(default=3, help_text='Chi phí Linh Thạch cho xuất PDF phân rã nét khi quá hạn'),
        ),
        migrations.AddField(
            model_name='coinconfig',
            name='writing_base_cost_en',
            field=models.IntegerField(default=1, help_text='Chi phí Coin nền cho Luyện Viết tiếng Anh'),
        ),
        migrations.AddField(
            model_name='coinconfig',
            name='writing_base_cost_zh',
            field=models.IntegerField(default=1, help_text='Chi phí Linh Thạch nền cho Luyện Viết tiếng Trung'),
        ),
        migrations.AddField(
            model_name='coinconfig',
            name='writing_increment_cost_en',
            field=models.IntegerField(default=1, help_text='Chi phí Coin tăng thêm cho mỗi 50 từ tiếp theo'),
        ),
        migrations.AddField(
            model_name='coinconfig',
            name='writing_increment_cost_zh',
            field=models.IntegerField(default=1, help_text='Chi phí Linh Thạch tăng thêm cho mỗi 50 chữ tiếp theo'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('EARN_STUDY', 'Kiếm từ học flashcard'), ('SPEND_CHAT_CREATE', 'Tạo AI Persona'), ('SPEND_CHAT_MSG', 'Gửi tin nhắn AI Chat'), ('REFUND', 'Hoàn trả do lỗi'), ('WEEKLY_REFILL', 'Hồi điểm hàng tuần'), ('ADMIN_ADJUST', 'Admin điều chỉnh'), ('PURCHASE', 'Mua bằng tiền'), ('TIER_RESET', 'Reset khi hết hạn subscription'), ('SPEND_WRITING_PRACTICE', 'Luyện viết AI'), ('SPEND_PDF_EXPORT', 'Xuất PDF quá hạn mức')], max_length=30),
        ),
    ]
