# Generated by Django 5.2.15 on 2026-07-16 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_coinconfig_pdf_normal_export_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Tên hiển thị (VD: 'Khung Hỏa Diệm')", max_length=200)),
                ('reward_type', models.CharField(choices=[('avatar_frame', 'Khung Avatar'), ('title', 'Danh hiệu'), ('bonus_coins', 'Điểm thưởng (Coin)'), ('item', 'Vật phẩm Cosmetic'), ('badge', 'Huy hiệu')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', help_text='URL ảnh cho khung/badge/item', max_length=500)),
                ('title_text', models.CharField(blank=True, default='', help_text='Text danh hiệu nếu type=title', max_length=100)),
                ('coin_amount', models.IntegerField(default=0, help_text='Số coin thưởng nếu type=bonus_coins')),
                ('rarity', models.CharField(choices=[('common', 'Phổ thông'), ('rare', 'Hiếm'), ('epic', 'Sử thi'), ('legendary', 'Huyền thoại')], default='common', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(choices=[('zh', 'Tiếng Trung'), ('en', 'Tiếng Anh'), ('all', 'Tất cả')], max_length=10)),
                ('required_level', models.IntegerField(help_text='Level cần đạt để nhận phần thưởng')),
                ('quantity', models.IntegerField(default=1, help_text='Số lượng vật phẩm thưởng')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='gamification.rewarditem')),
            ],
            options={
                'ordering': ['lang', 'required_level'],
                'unique_together': {('lang', 'required_level', 'reward_item')},
            },
        ),
        migrations.CreateModel(
            name='EXPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=10)),
                ('source_type', models.CharField(choices=[('STUDY_SESSION', 'Hoàn thành lật thẻ flashcard'), ('CHAT_PEER', 'Chat AI đồng cấp'), ('CHAT_SUPERIOR', 'Chat AI cấp trên'), ('CHAT_REWARD', 'Thưởng từ chat'), ('CHAT_PUNISH', 'Phạt từ chat'), ('ADMIN_ADJUST', 'Admin điều chỉnh'), ('QUEST_COMPLETE', 'Hoàn thành nhiệm vụ')], max_length=30)),
                ('amount', models.IntegerField(help_text='Dương = cộng EXP, Âm = trừ EXP')),
                ('level_before', models.IntegerField()),
                ('level_after', models.IntegerField()),
                ('exp_before', models.IntegerField(help_text='current_exp trước giao dịch')),
                ('exp_after', models.IntegerField(help_text='current_exp sau giao dịch')),
                ('idempotency_key', models.CharField(blank=True, help_text="Khóa duy nhất đảm bảo mỗi giao dịch EXP chỉ được xử lý 1 lần. Format: '{source_type}:{user_id}:{lang}:{message_id_or_date}'", max_length=255, null=True, unique=True)),
                ('reference_id', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'lang', 'created_at'], name='gamificatio_user_id_dce899_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='uq_exp_transaction_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='LevelRewardLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=10)),
                ('level', models.IntegerField(help_text='Level tại thời điểm nhận thưởng')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_reward_logs', to=settings.AUTH_USER_MODEL)),
                ('reward_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.rewardrule')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'lang', 'level'], name='gamificatio_user_id_eb206e_idx')],
                'unique_together': {('user', 'lang', 'level', 'reward_rule')},
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False, help_text='Đang trang bị/sử dụng')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('reward_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inventories', to='gamification.rewarditem')),
                ('source_rule', models.ForeignKey(blank=True, help_text='Rule đã grant vật phẩm này', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.rewardrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'reward_item'], name='gamificatio_user_id_31a164_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLanguageLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(choices=[('zh', 'Tiếng Trung'), ('en', 'Tiếng Anh')], max_length=10)),
                ('level', models.IntegerField(default=1)),
                ('current_exp', models.IntegerField(default=0, help_text='EXP tích lũy trong level hiện tại')),
                ('total_exp', models.IntegerField(default=0, help_text='Tổng EXP tích lũy từ đầu (không bao giờ giảm)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'lang'], name='gamificatio_user_id_093561_idx')],
                'unique_together': {('user', 'lang')},
            },
        ),
    ]
