# Generated by Django 5.2.15 on 2026-07-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_rewarditem_rewardrule_exptransaction_levelrewardlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarditem',
            name='ui_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Cấu hình hiển thị động ở Frontend'),
        ),
    ]
