# Generated by Django 5.2.15 on 2026-07-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_rewarditem_ui_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewarditem',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='URL hoặc đường dẫn ảnh cho khung/badge/item', max_length=500),
        ),
    ]
