# Generated by Django 5.2.15 on 2026-07-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_alter_rewarditem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransaction',
            name='shop_balance_after',
            field=models.IntegerField(default=0, help_text='Snapshot shop_balance sau giao dịch'),
        ),
        migrations.AddField(
            model_name='coinwallet',
            name='shop_balance',
            field=models.PositiveIntegerField(default=0, help_text='Hạn ngạch cửa hàng (Thần thạch/Đá quý) — chỉ dùng mua shop'),
        ),
        migrations.AddField(
            model_name='rewarditem',
            name='is_sellable',
            field=models.BooleanField(default=False, help_text='Có thể mua bằng tiền/coin trong shop không'),
        ),
        migrations.AddField(
            model_name='rewarditem',
            name='price_free',
            field=models.PositiveIntegerField(default=0, help_text='Giá bằng coin free (0 = không bán bằng free)'),
        ),
        migrations.AddField(
            model_name='rewarditem',
            name='price_paid',
            field=models.PositiveIntegerField(default=0, help_text='Giá bằng coin paid (0 = không bán bằng paid)'),
        ),
        migrations.AddField(
            model_name='rewarditem',
            name='price_shop',
            field=models.PositiveIntegerField(default=0, help_text='Giá bằng Thần thạch/Đá quý (0 = không bán bằng shop quota)'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='balance_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('free', 'Free'), ('shop', 'Shop (Thần thạch/Đá quý)')], help_text='Nguồn cấp thực tế bị tác động', max_length=10),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('EARN_STUDY', 'Kiếm từ học flashcard'), ('SPEND_CHAT_CREATE', 'Tạo AI Persona'), ('SPEND_CHAT_MSG', 'Gửi tin nhắn AI Chat'), ('REFUND', 'Hoàn trả do lỗi'), ('WEEKLY_REFILL', 'Hồi điểm hàng tuần'), ('ADMIN_ADJUST', 'Admin điều chỉnh'), ('PURCHASE', 'Mua bằng tiền'), ('TIER_RESET', 'Reset khi hết hạn subscription'), ('SPEND_WRITING_PRACTICE', 'Luyện viết AI'), ('SPEND_PDF_EXPORT', 'Xuất PDF quá hạn mức'), ('SHOP_PURCHASE', 'Mua vật phẩm tại Cửa Hàng')], max_length=30),
        ),
    ]
