# Generated by Django 5.2.9 on 2026-08-16 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0010_cointransaction_shop_balance_after_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tên hiển thị của nhiệm vụ", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Mô tả nhiệm vụ"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="task_alt",
                        help_text="Material symbol icon name",
                        max_length=100,
                    ),
                ),
                (
                    "quest_type",
                    models.CharField(
                        choices=[
                            ("daily", "Nhiệm vụ hàng ngày"),
                            ("weekly", "Nhiệm vụ hàng tuần"),
                            ("achievement", "Thành tựu"),
                            ("event", "Sự kiện / Theo mùa"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("zh", "Tiếng Trung"),
                            ("en", "Tiếng Anh"),
                            ("all", "Tất cả"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("study_words", "Học từ vựng (flashcard)"),
                            ("study_sessions", "Hoàn thành phiên học"),
                            ("chat_messages", "Gửi tin nhắn AI Chat"),
                            ("streak_days", "Duy trì streak liên tiếp"),
                            ("reach_level", "Đạt cấp độ"),
                            ("login_days", "Đăng nhập (ngày khác nhau)"),
                            ("earn_coins", "Kiếm coin (free) từ học"),
                            ("writing_sessions", "Hoàn thành bài luyện viết"),
                            ("daily_target_met", "Hoàn thành mục tiêu hàng ngày"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "target_value",
                    models.IntegerField(
                        default=1, help_text="Số lượng cần đạt để hoàn thành"
                    ),
                ),
                ("reward_exp", models.IntegerField(default=0, help_text="EXP thưởng")),
                (
                    "reward_coins",
                    models.IntegerField(default=0, help_text="Coin (free) thưởng"),
                ),
                (
                    "reward_item_quantity",
                    models.IntegerField(
                        default=1, help_text="Số lượng vật phẩm thưởng"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Thời điểm bắt đầu áp dụng (cho event quest)",
                        null=True,
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="Thời điểm kết thúc áp dụng (cho event quest)",
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, help_text="Thứ tự hiển thị"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reward_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vật phẩm phần thưởng (nếu có)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quest_definitions",
                        to="gamification.rewarditem",
                    ),
                ),
            ],
            options={
                "ordering": ["quest_type", "sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserQuestProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_value",
                    models.IntegerField(default=0, help_text="Tiến độ hiện tại"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "Đang thực hiện"),
                            ("completed", "Đã hoàn thành"),
                            ("claimed", "Đã nhận thưởng"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        help_text="Ngày bắt đầu chu kỳ (daily=hôm nay, weekly=thứ 2 tuần này, achievement=null)",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True, help_text="Ngày kết thúc chu kỳ", null=True
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="gamification.questdefinition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestClaimLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("exp_granted", models.IntegerField(default=0)),
                ("coins_granted", models.IntegerField(default=0)),
                ("item_quantity_granted", models.IntegerField(default=0)),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item_granted",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gamification.rewarditem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_claim_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.questdefinition",
                    ),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.userquestprogress",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="userquestprogress",
            index=models.Index(
                fields=["user", "quest", "period_start"],
                name="gamificatio_user_id_8131a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userquestprogress",
            index=models.Index(
                fields=["user", "status"], name="gamificatio_user_id_bff857_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userquestprogress",
            index=models.Index(
                fields=["period_end", "status"], name="gamificatio_period__1edd05_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userquestprogress",
            unique_together={("user", "quest", "period_start")},
        ),
        migrations.AddIndex(
            model_name="questclaimlog",
            index=models.Index(
                fields=["user", "claimed_at"], name="gamificatio_user_id_d6ef7a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questclaimlog",
            unique_together={("user", "quest", "period_start")},
        ),
    ]
