# Generated by Django 5.2.15 on 2026-07-14 09:31

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_zh', '0009_alter_zhword_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='zhword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['radical'], name='zhword_radical_gin', opclasses=['jsonb_path_ops']),
        ),
    ]
