# Generated by Django 5.2.15 on 2026-07-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_add_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumelimitconfig',
            name='translation_en_limit',
            field=models.PositiveIntegerField(default=300, help_text='Hạn mức ký tự dịch thuật Tiếng Anh/Việt'),
        ),
        migrations.AddField(
            model_name='volumelimitconfig',
            name='translation_zh_limit',
            field=models.PositiveIntegerField(default=150, help_text='Hạn mức ký tự dịch thuật Tiếng Trung'),
        ),
    ]
