# Generated by Django 5.2.15 on 2026-07-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_zhenmapping_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZhEnMapping',
        ),
    ]
