# Generated by Django 5.2.15 on 2026-07-11 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension, VectorField


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoyue_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ChatSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(help_text='Summarized conversation text (max 3 sentences)')),
                ('embedding', VectorField(dimensions=768, help_text='Vector embedding from text-embedding-004', null=True)),
                ('message_count', models.IntegerField(default=6, help_text='Number of messages summarized in this entry')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'created_at'], name='xiaoyue_cha_user_id_44927f_idx'),
                ],
            },
        ),
    ]
