# Generated by Django 5.2.15 on 2026-07-12 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoyue_chat', '0002_chatsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPersona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_birth_year', models.IntegerField()),
                ('personality_type', models.CharField(max_length=50)),
                ('personality_desc', models.TextField()),
                ('avatar_emoji', models.CharField(max_length=20)),
                ('context_setting', models.CharField(max_length=50)),
                ('learning_language', models.CharField(max_length=10)),
                ('user_level', models.CharField(max_length=50)),
                ('user_honorific', models.CharField(max_length=100)),
                ('agent_self_ref', models.CharField(max_length=100)),
                ('relation_type', models.CharField(default='default', max_length=50)),
                ('joy_sensitivity', models.FloatField(default=1.0)),
                ('joy_decay_rate', models.FloatField(default=0.4)),
                ('sad_sensitivity', models.FloatField(default=0.5)),
                ('sad_decay_rate', models.FloatField(default=0.6)),
                ('joy_current', models.FloatField(default=0.5)),
                ('sad_current', models.FloatField(default=0.1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='chatsummary',
            new_name='xiaoyue_cha_user_id_8f1f76_idx',
            old_name='xiaoyue_cha_user_id_44927f_idx',
        ),
        migrations.AddField(
            model_name='chatpersona',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_personas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='xiaoyue_chat.chatpersona'),
        ),
        migrations.AddField(
            model_name='chatsummary',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='xiaoyue_chat.chatpersona'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['persona', 'timestamp'], name='xiaoyue_cha_persona_b74456_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsummary',
            index=models.Index(fields=['persona', 'created_at'], name='xiaoyue_cha_persona_7830cd_idx'),
        ),
        migrations.AddIndex(
            model_name='chatpersona',
            index=models.Index(fields=['user', '-updated_at'], name='xiaoyue_cha_user_id_79a65d_idx'),
        ),
    ]
