# Generated by Django 5.2.15 on 2026-07-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoyue_chat', '0003_chatpersona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatpersona',
            name='age_diff',
            field=models.IntegerField(default=0),
        ),
    ]
