# Generated by Django 5.2.15 on 2026-07-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoyue_chat', '0004_chatpersona_age_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatpersona',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
