# Generated by Django 5.2.15 on 2026-07-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoyue_chat', '0005_chatpersona_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatpersona',
            name='age_diff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatpersona',
            name='agent_birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
