# Generated by Django 5.2.15 on 2026-07-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('true_false', 'True/False - Đúng Sai'), ('multiple_choice', 'Multiple Choice - Trắc nghiệm'), ('fill_blank', 'Fill in Blank - Điền từ'), ('matching', 'Matching - Nối'), ('ordering', 'Ordering - Sắp xếp'), ('essay', 'Essay - Tự luận')], max_length=30),
        ),
    ]
