# Generated by Django 5.2.15 on 2026-07-05 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_id', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField(help_text='Nội dung đoạn văn dài')),
                ('ordering', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='exams.section')),
            ],
            options={
                'db_table': 'exams_paragraph',
                'ordering': ['section', 'ordering'],
                'unique_together': {('section', 'paragraph_id')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='paragraph',
            field=models.ForeignKey(blank=True, help_text='Đoạn văn đọc hiểu của câu hỏi này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.paragraph'),
        ),
    ]
