# Generated by Django 5.2.15 on 2026-07-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_paragraph_question_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='section',
            name='passage',
            field=models.JSONField(blank=True, help_text='Đoạn văn đọc hiểu của section này (chứa title và content)', null=True),
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
