# Generated by Django 5.2.15 on 2026-07-15 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board_type', models.CharField(choices=[('coin_paid', 'Xếp hạng Coin/Linh Thạch (Paid)'), ('coin_free', 'Xếp hạng Coin/Linh Thạch (Free)'), ('total_likes', 'Xếp hạng Like'), ('weekly_words', 'Xếp hạng Từ thuộc tuần'), ('max_streak', 'Xếp hạng Streak')], max_length=20)),
                ('lang', models.CharField(choices=[('zh', 'Chinese'), ('en', 'English')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'leaderboard_snapshot',
                'indexes': [models.Index(fields=['board_type', 'lang', '-created_at'], name='leaderboard_board_t_3d5f9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('score', models.BigIntegerField()),
                ('username', models.CharField(max_length=150)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='leaderboard.leaderboardsnapshot')),
            ],
            options={
                'db_table': 'leaderboard_entry',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['snapshot', 'rank'], name='leaderboard_snapsho_8365e5_idx')],
                'unique_together': {('snapshot', 'user')},
            },
        ),
    ]
