# Generated by Django 5.2.15 on 2026-07-11 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_firebase_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('fact', 'Fact'), ('error', 'Repeated Error'), ('context', 'Conversational Context')], max_length=32)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding list', null=True)),
                ('importance', models.IntegerField(default=3, help_text='Importance level (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
