# Generated by Django 5.2.15 on 2026-07-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermemory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMemory',
        ),
    ]
