# Generated by Django 5.2.15 on 2026-07-15 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(choices=[('zh', 'Chinese'), ('en', 'English')], db_index=True, max_length=10)),
                ('content', models.TextField(max_length=2000)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_forumpost',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1000)),
                ('like_count', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_postcomment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word_id', models.UUIDField(db_index=True)),
                ('lang', models.CharField(choices=[('zh', 'Chinese'), ('en', 'English')], max_length=10)),
                ('content', models.TextField(max_length=500)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_wordcomment',
            },
        ),
        migrations.CreateModel(
            name='WordCommentVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.wordcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_comment_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_wordcommentvote',
            },
        ),
        migrations.CreateModel(
            name='CommunityAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('post', 'Forum Post'), ('post_comment', 'Post Comment'), ('word_comment', 'Word Comment')], max_length=20)),
                ('object_id', models.UUIDField(db_index=True)),
                ('reason', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Chấp nhận (Phục hồi)'), ('rejected', 'Từ chối (Giữ ẩn)')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_appeal',
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('post', 'Forum Post'), ('post_comment', 'Post Comment'), ('word_comment', 'Word Comment')], max_length=20)),
                ('object_id', models.UUIDField(db_index=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam / Quảng cáo'), ('harassment', 'Quấy rối / Bắt nạt'), ('inappropriate', 'Nội dung không phù hợp'), ('misinformation', 'Thông tin sai lệch'), ('other', 'Lý do khác')], max_length=20)),
                ('detail', models.TextField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_report',
                'indexes': [models.Index(fields=['content_type', 'object_id', 'created_at'], name='community_r_content_48a584_idx')],
                'unique_together': {('reporter', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='PostBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='community.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_postbookmark',
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='PostCommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.postcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_postcommentlike',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_postlike',
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.AddIndex(
            model_name='wordcomment',
            index=models.Index(fields=['user', 'lang', '-created_at'], name='community_w_user_id_6099bf_idx'),
        ),
        migrations.AddIndex(
            model_name='wordcomment',
            index=models.Index(fields=['word_id', 'lang', '-score'], name='community_w_word_id_98db58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wordcomment',
            unique_together={('user', 'word_id', 'lang')},
        ),
        migrations.AlterUniqueTogether(
            name='wordcommentvote',
            unique_together={('user', 'comment')},
        ),
    ]
