# Generated by Django 5.2.15 on 2026-07-15 00:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_exercises', '0002_userflashcardhistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('general', 'Luyện viết tự do'), ('deep_practice', 'Luyện viết sâu theo từ')], default='general', max_length=20)),
                ('sentence', models.TextField(verbose_name='Đoạn văn/Câu do học sinh viết')),
                ('target_word', models.CharField(blank=True, default='', max_length=255, verbose_name='Từ vựng mục tiêu (nếu có)')),
                ('lang', models.CharField(default='zh', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('cost', models.IntegerField(default=0, verbose_name='Số điểm đã khấu trừ')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='Kết quả chấm điểm AI')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='flashcard_e_user_id_5aa60a_idx'), models.Index(fields=['user', 'created_at'], name='flashcard_e_user_id_ace4b2_idx')],
            },
        ),
    ]
